# Entity and item drop limits configuration. It will only clear parts that exceed the limits.
# 区块实体、掉落物限制配置，只会清理超出的部分
entity-limits:
  # Default maximum number of entities allowed per chunk (all entities except those with special configurations)
  # 默认每个区块允许的最大实体数量（除特殊配置外的所有实体）
  default-limit: 100
  # Maximum number of item entities allowed (item drops), note that this counts the merged stack of items
  # 物品实体的最大数量限制（掉落物）, 注意计算的是合并后的实体堆数量
  item-limit: 300
  # Check interval (in game ticks, 20 ticks = 1 second)
  # 检查间隔（单位：游戏刻，20 ticks = 1秒）
  check-interval-ticks: 200  # This means the check occurs every 10 seconds / 即每10秒检查一次
  # ------------en------------
  # Whether to check chunks around the player. 0 means disabled.
  # Example: If chunk-check-radius: 1 and default-limit: 100, the total limit for all chunks (3x3) within radius 1 around the player is also 100. Single-chunk limits still apply.
  # ------------zh------------
  # 是否包含检查玩家周围的区块，0表示禁用
  # 例如: 当chunk-check-radius: 1, default-limit: 100时, 则玩家周围半径1内的所有区块(3x3)的总限制也为100, 单区块限制也同时生效
  chunk-check-radius: 1
  # ------------en------------
  # Multiplier for entity limits in chunks around the player.
  # Example: If chunk_entity_multiplier: 1.5, chunk-check-radius: 1, and default-limit: 100, the entity limit for all chunks (3x3) within radius 1 becomes 100 * 1.5.
  # ------------zh------------
  # 玩家周围的区块实体限制倍数
  # 例如: 当chunk_entity_multiplier: 1.5, chunk-check-radius: 1, default-limit: 100时, 则玩家周围半径1内的所有区块(3x3)的实体限制为100*1.5
  chunk_entity_multiplier: 1.5
  # ------------en------------
  # Multiplier for item entity limits in chunks around the player.
  # Example: If chunk_item_multiplier: 1.5, chunk-check-radius: 1, and default-limit: 100, the item limit for all chunks (3x3) within radius 1 becomes 100 * 1.5.
  # ------------zh------------
  # 玩家周围的区块物品实体限制倍数
  # 例如: 当chunk_entity_multiplier: 1.5, chunk-check-radius: 1, default-limit: 100时, 则玩家周围半径1内的所有区块(3x3)的物品限制为100*1.5
  chunk_item_multiplier: 1.5
  # Ignored entity types (these will not be counted or cleared)
  # 忽略的实体类型（不会被计数和清理）
  ignored-types:
    - IRON_GOLEM    # Iron Golem / 铁傀儡
  # Ignored item types (these will not be counted or cleared)
  # 忽略的物品类型（不会被计数和清理）
  ignored-items:
    - DIAMOND           # Diamond / 钻石
    - NETHERITE_INGOT   # Netherite Ingot / 下界合金锭
    - ENCHANTED_GOLDEN_APPLE # Enchanted Golden Apple / 附魔金苹果
  # Custom entity limits (override the default limits)
  # 自定义实体限制（覆盖默认限制）
  custom-limits:
    ZOMBIE: 200     # Maximum number of Zombies / 僵尸最大数量
    CREEPER: 200    # Maximum number of Creepers / 苦力怕最大数量
    ZOMBIFIED_PIGLIN: 200  # Maximum number of Zombified Piglins / 猪人最大数量

# Protection Settings
# 保护设置
protection:
  # Protect entities with custom names
  # 保护被命名的实体
  protect-named-entities: true
  # Protect leashed mobs (horses/donkeys excluded by default)
  # 保护被拴住的实体
  protect-leashed-entities: true
  # Prevent harming tamed pets (dogs/cats/parrots)
  # 保护驯服的动物
  protect-tamed-animals: true

# Notification settings
# 通知设置
settings:
  # Controls whether cleaning reports and limit warnings are sent to the console and online admins. Default: true
  # 控制是否发送清理报告和超限警告到控制台和在线管理员，默认：true
  enable-notifications: true
  # Warning notification percentage (0-100). 0 means no warning, only notify players in the current chunk
  # 预警通知百分比（0-100），0表示禁用预警，仅通知当前区块的玩家
  notify-threshold: 90
  # Warning cooldown time, in seconds
  # 预警冷却时间，单位秒
  notify-cooldown: 10
  # Player notification scope
  # 玩家通知范围
  notification-radius: 128.0
  # Set to true to enable performance monitoring
  # 设为 true 启用性能监控
  performance-monitoring: false
  # Language option (en/zh)
  # 语言选项（en/zh）
  language: en