name: ChunkEntityLimiter
version: 1.3.0
main: cn.kurt6.ChunkLimiter.ChunkEntityLimiter
api-version: 1.16
description: 高性能区块实体限制与清理插件
author: Kurt
folia-supported: true

commands:
  chunklimit:
    description: 区块实体限制管理命令
    aliases: [climit, cl]
    usage: |
      /chunklimit reload - 重载配置
      /chunklimit stats - 查看区块统计
      /chunklimit notify [report|warning] [none|op|all] - 设置通知范围
      /chunklimit performance - 查看性能监控

permissions:
  chunklimiter.reload:
    description: 允许重载配置
    default: op
  chunklimiter.notify:
    description: 允许接收清理通知
    default: op
  chunklimiter.stats:
    description: 允许查看区块统计
    default: true
  chunklimiter.performance:
    description: 允许查看性能监控
    default: op