name: ChunkEntityLimiter
version: 1.0.0
main: cn.kurt6.ChunkLimiter.ChunkEntityLimiter
api-version: 1.21
authors: [Kurt]
folia-supported: true
commands:
  entitylimiterreload:
    description: 重载插件配置
    usage: /entitylimiterreload
    permission: chunklimiter.reload
  chunkinfo:
    description: 查看当前区块的物品统计
    usage: /chunkinfo
    permission: chunklimiter.info
permissions:
  chunklimiter.reload:
    description: 允许重载插件配置
    default: op
  chunklimiter.info:
    description: 允许查看区块信息
    default: true